on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: udemyml4818172403.azurecr.io
        username: ${{ secrets.acr_udemyml4818172403_username }}
        password: ${{ secrets.acr_udemyml4818172403_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t udemyml4818172403.azurecr.io/cluster97:${{ github.sha }}
        docker push udemyml4818172403.azurecr.io/cluster97:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_cluster97_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep cluster97c3d1 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace cluster97c3d1`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: cluster97c3d1
        container-registry-url: udemyml4818172403.azurecr.io
        container-registry-username: ${{ secrets.acr_udemyml4818172403_username }}
        container-registry-password: ${{ secrets.acr_udemyml4818172403_password }}
        secret-name: cluster97dockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: cluster97c3d1
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          udemyml4818172403.azurecr.io/cluster97:${{ github.sha }}
        imagepullsecrets: |
          cluster97dockerauth